#!/bin/bash
git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
brew install fish
brew install neovim
brew install tmux
brew install tig
# brew install python3
brew install reattach-to-user-namespace
brew install vifm
brew install coreutils
brew install bro
brew install pyenv
brew install pyenv-virtualenv
pyenv install 3.8.5
pyenv install 2.7.18
pyenv virtualenv 3.8.5 shell3
pyenv virtualenv 2.7.18 shell2
pyenv global shell3 shell2
pip3 install neovim-remote
gem install tmuxinator
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
pip install -U adjspecies
defaults write -g InitialKeyRepeat -int 12
defaults write -g KeyRepeat -int 1
defaults write -g ApplePressAndHoldEnabled -bool false

# Fully expand the save prompt by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Sleep on a slightly long power button press
defaults write com.apple.loginwindow PowerButtonSleepsSyste -bool yes

# Don't put a DS store on a network drive
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Empty Trash securely by default
defaults write com.apple.finder EmptyTrashSecurely -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Ask for a password immediately after sleeping
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0


