#!/bin/bash
git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
brew install fish
brew install neovim
brew install tmux
brew install tig
brew install python3
brew install reattach-to-user-namespace
brew install vifm
brew install coreutils
brew install bro
brew install pyenv
brew install pyenv-virtualenv
pip3 install neovim-remote
gem install tmuxinator
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
pip install -U adjspecies
